spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=julian
spring.datasource.password=

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity